test : assoc_array.c test_assoc_array.c
	gcc -g assoc_array.c test_assoc_array.c -o test

fifo : fifo.c fifo_test.c
	gcc fifo.c fifo_test.c -o fifo

test_bi : assoc_array.c bi_assoc_array.c bi_array_test.c
	gcc assoc_array.c bi_assoc_array.c bi_array_test.c -o test_bi

test_linked_list : assoc_array.c linked_list.c test_linked_list.c
	gcc assoc_array.c linked_list.c test_linked_list.c -o testll